name: "snyk-windows"
description: "setup snyk on windows"
inputs:
  command:
    description: "Which Snyk command to run, defaults to test"
    default: test
  args:
    description: "Additional arguments to pass to Snyk"
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: gh release download -R snyk/cli  --pattern snyk-win.exe
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - shell: pwsh
      env:
        INPUTS_COMMAND: ${{ inputs.command }}
        INPUTS_ARGS: ${{ inputs.args }}
      run: .\snyk-win.exe $INPUTS_COMMAND $INPUTS_ARGS
